#! /usr/bin/env python
# encoding: utf-8

def configure(cnf):
    cnf.define('LIBDIR', cnf.env['LIBDIR'])
    cnf.define('DATADIR', cnf.env['INSTALL_DATA_DIR'])
    cnf.write_config_header('config.h')

def build(bld):
    srcs = 'Log.cpp FileIO.cpp Input.cpp BinIO.cpp BinIO_private.cpp MacCompatibility.cpp Frustum.cpp GameDraw.cpp GameInitDispose.cpp GameTick.cpp Globals.cpp Lights.cpp Models.cpp Objects.cpp openal_wrapper.cpp Person.cpp Quaternions.cpp Skeleton.cpp Skybox.cpp Sprites.cpp Terrain.cpp Text.cpp TGALoader.cpp Weapons.cpp'
    bld.stlib(source=srcs, target='ragaru', name='libragaru', use=['SDL2', 'OPENAL', 'OGG', 'VORBISFILE', 'GLIBMM'])
    bld.program(source='Main.cpp', target='ragaru', features='c cxx cxxprogram', use=['libragaru', 'JPEG', 'OGG', 'GLIBMM', 'GLU', 'OPENAL', 'SDL2', 'LIBPNG', 'ZLIB', 'VORBISFILE'], includes='.')

